const Product = require("./models/product")
const dbConnect = require("./db/dbConnect")
require("dotenv").config()
const items = require("./items.json")

dbConnect(process.env.DBCONNECT)
.then(Product.deleteMany())
.then(Product.create(items))
.then(() => console.log("Populated!"))
.catch(err => console.log(err)) 